# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d78514dacb881bdfcd86a4192d585b5b196b71be5532a209a79ad62c1e5051ea49daa8253e157d2ea2c19ea512cce2ce4369e31c265f9772aba27739176b8e0

test:
  secret_key_base: 4c36683bd9dcd87e287bef90462309d5dac9d66acaac6fa7b574985b151591d4931d5c34bb4d89c59b3ebaf3188edeca44447bdee8c60dda2c87d4bf466900af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
